### ISSUE TITLE
Documentation: Caliban Default Creds

### ISSUE THREAD

**Issue by jordanrule** [google/caliban#86]
Couple issues
1) gcloud service account credentials now required (as `.caliban_default_creds`) but not documented

2) Even when I supply working credentials, `gcloud auth` inside Docker is not working:
```
Step 9/18 : RUN gcloud auth activate-service-account --key-file=/.creds/credentials.json &&   git config --global credential.'https://source.developers.google.com'.helper gcloud.sh
 ---> Running in ef0260e778f6
ERROR: (gcloud.auth.activate-service-account) The .json key file is not in a valid format.
The command '/bin/sh -c gcloud auth activate-service-account --key-file=/.creds/credentials.json &&   git config --global credential.'https://source.developers.google.com'.helper gcloud.sh' returned a non-zero code: 1
E0820 10:49:44.640692 4603461056 main.py:165] Docker failed with error code 1.
```

Confirmation it works external to Docker:
```
gcloud auth activate-service-account --key-file ...
Activated service account credentials for: [...]
```

**Comment by jordanrule** [comment]
I got past this by passing in `--cloud_key` - seems like it should be added to Getting Started, can open a PR if desired.

**Comment by jordanrule** [comment]
OK, now I see the documentation: https://caliban.readthedocs.io/en/latest/cloud/service_account.html , and that the documentation just assumes `GOOGLE_APPLICATION_CREDENTIALS` is set to a service account (not user account).  None of this is a big deal, just some clarification on credentials would be good so people (particularly scientists) don't bounce before getting everything running or at least knowing what to ask for.  Some clarification on why credentials are needed to run locally would be good too?

**Comment by sritchie** [comment]
Hey @jordanrule! Thanks for this report - this is definitely a bug if it's on Caliban 0.3.0 or later. Can I ask what version of Caliban you're on? There did indeed used to be a service account credential requirement, before I figured out how I could hijack the normal, `gcloud auth login` credentials to do job submissions. That's why I dropped the service account requirements from the main docs.

I think that the code should work the way you expect (with no requirement here) on the latest published version of Caliban.

You've also discovered an internal trick we use. Here's my current understanding of how google SAYS credentials work:

-  If you set `GOOGLE_APPLICATION_CREDENTIALS`, it has to point to a service account JSON key, as you've described, not anything else.
- That key almost always lives in some directory like `~/.config`, somewhere user-local.
- Docker isn't able, by design, to access any files outside of the folder where it's running. So, as a hack, if you HAVE set that environment variable, we create a temporary copy in the project folder, then delete it when the caliban command finishes running. It's not that elegant... I would use a temporary filename, but that would bust the Docker cache. That's why you see the hidden filename `.caliban_default_creds`; that's the static name of the temp file.

### What to do?
So how to solve your problem? I think if you upgrade Caliban, this will go away, assuming you've got `GOOGLE_APPLICATION_CREDENTIALS` pointed at a valid service account key (and that you delete your copy of the temporary file, so Caliban can write and delete it).

If you've got `GOOGLE_APPLICATION_CREDENTIALS` pointed at any OTHER type of creds, like the "application default credentials", then you'll see failures, I expect.

Okay, let me know what you think! Let me know if I've misunderstood anything, and especially if the problem persists after an upgrade. The credentials part of all of this is annoying and we want to make the experience easy for folks.
